server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    # \u5F53\u524D\u6570\u636E\u6E90\u64CD\u4F5C\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql\u9A71\u52A8\u7C7B
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.239.222:9001/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: uniseqroot
    password: Pagoda@2017
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cloud.soft.entities

eureka:
  client:
    #\u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u8FDBEurekaServer\u9ED8\u8BA4\u4E3Atrue
    register-with-eureka: true
    #\u662F\u5426\u4ECEEurekaServer\u6293\u53D6\u5DF2\u6709\u7684\u6CE8\u518C\u6D88\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue\uFF0C\u5355\u8282\u70B9\u65E0\u6240\u8C13\uFF0C\u96C6\u7FA4\u5FC5\u987B\u8BBE\u7F6E\u4E3Atrue\u624D\u80FD\u914D\u5408ribbon\u4F7F\u7528\u8D1F\u8F7D\u5747\u8861
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #eureka上显示的负载名字为payment8002不是默认的  IP名:应用名:应用端口名
    instance-id: payment8002
      #鼠标放在eureka的负载链接上显示ip地址
    prefer-ip-address: true
